Recognize both the eDelivery and OTN file names
The base database release files on the oracle.com have different naming convention. This change makes it possible to support both OTN and eDelivery file names.

diff --git a/roles/check-swlib/tasks/main.yml b/roles/check-swlib/tasks/main.yml
--- a/roles/check-swlib/tasks/main.yml
+++ b/roles/check-swlib/tasks/main.yml
@@ -16,13 +16,27 @@
 - name: check-swlib | Validate base software release
   shell: |
     set -o pipefail
-    {% for i in item.files %}
-      gsutil ls -L gs://{{ swlib_mount_src }}/{{ i }} | \
-        awk '/md5/ { print $3 }'
+    {% for f in item.files %}
+    if gsutil ls gs://{{ swlib_mount_src }}/{{ f.name }} >/dev/null 2>&1; then
+      f_name="{{ f.name }}"
+      md5sum="{{ f.md5sum }}"
+    else
+      f_name="{{ f.alt_name | default('x') }}"
+      md5sum="{{ f.alt_md5sum | default('x') }}"
+    fi
+    actual_md5=$(gsutil ls -L gs://{{ swlib_mount_src }}/${f_name} | awk '/md5/ { print $3 }')
+    if [ $? -ne 0 ] ; then
+      echo "ERROR locating {{ f.name }} {{ f.alt_name | default('') }}"
+      exit 1;
+    else
+      if [ "$actual_md5" != "$md5sum" ]; then
+        echo "ERROR locating {{ item.name }}: md5 mismatch for ${f_name}"
+        exit 1
+      fi  
+    fi
     {% endfor %}
   args:
     executable: /bin/bash
-  failed_when: item.md5sum != base_repo_files.stdout_lines
   changed_when: false
   ignore_errors: true
   with_items:
@@ -83,15 +97,6 @@
   with_items:
     - "{{ patch_repo_files.results }}"
     - "{{ opatch_repo_files.results }}"
-
-- name: check-swlib | Report MD5 mismatches (base)
-  fail:
-    msg: |
-      MD5 mismatch: expected {{ item.item.md5sum }} got {{ item.stdout_lines }}
-      for {{ item.item.name }} {{ item.item.files }}
-  when: item.failed is defined and item.failed
-  with_items:
-    - "{{ base_repo_files.results }}"
 
 - name: check-swlib | Report MD5 mismatches (patch)
   fail:
