Recognize both the eDelivery and OTN file names
The base database release files on the oracle.com have different naming convention. This change makes it possible to support both OTN and eDelivery file names.

diff --git a/roles/check-swlib/tasks/main.yml b/roles/check-swlib/tasks/main.yml
--- a/roles/check-swlib/tasks/main.yml
+++ b/roles/check-swlib/tasks/main.yml
@@ -16,34 +16,28 @@
 - name: check-swlib | Validate base software release
   shell: |
     set -o pipefail
-    {% for f in item.files %}
-    if gsutil -q stat gs://"{{ swlib_mount_src }}"/"{{ f.name }}"; then
-      f_name="{{ f.name }}"
-      expected_md5="{{ f.md5sum }}"
+    if gsutil -q stat gs://"{{ swlib_mount_src }}"/"{{ item.1.name }}"; then
+      f_name="{{ item.1.name }}"
+      expected_md5="{{ item.1.md5sum }}"
     else
-      # use alternative file name
-      f_name="{{ f.alt_name | default('x') }}"
-      expected_md5="{{ f.alt_md5sum | default('x') }}"
+      f_name="{{ item.1.alt_name | default('x') }}"
+      expected_md5="{{ item.1.alt_md5sum | default('x') }}"
     fi
     actual_md5=$(gsutil ls -L gs://"{{ swlib_mount_src }}"/"${f_name}" | awk '/md5/ { print $3 }')
-    if [[ $? -ne 0 ]] ; then
-      echo "ERROR locating {{ f.name }}{% if f.alt_name is defined and f.alt_name | length > 0 %} or {{ f.alt_name }}{% endif %}"
+    if [[ "$?" -ne "0" ]] ; then
+      echo "ERROR locating {{ item.1.name }}{% if item.1.alt_name is defined and item.1.alt_name | length > 0 %} or {{ item.1.alt_name }}{% endif %}"
     else
       if [[ "$actual_md5" != "$expected_md5" ]]; then
-        echo "ERROR in {{ item.name }} md5: expected $expected_md5, but got $actual_md5 for ${f_name}"
+        echo "ERROR in {{ item.0.name }} md5: expected $expected_md5, but got $actual_md5 for ${f_name}"
       fi
     fi
-    {% endfor %}
   args:
     executable: /bin/bash
   failed_when: "'ERROR' in base_repo_files.stdout"
   changed_when: false
   ignore_errors: true
-  with_items:
-    - "{{ gi_software }}"
-    - "{{ gi_interim_patches }}"
-    - "{{ rdbms_software }}"
-  when: item.version == oracle_ver
+  loop: "{{ (gi_software + gi_interim_patches + rdbms_software) | subelements('files') }}"
+  when: item.0.version == oracle_ver
   register: base_repo_files
 
 - name: check-swlib | Validate patchsets
@@ -85,7 +79,7 @@
 
 - name: check-swlib | Report gsutil failures (base)
   fail:
-    msg: "ERROR locating {{ item.item.name }} {{ item.item.files }}: {{ item.stderr_lines }}"
+    msg: "ERROR locating {{ item.item.0.name }} {{ item.item.1.name }}: {{ item.stdout }}"
   when: item.failed_when_result is defined and item.failed_when_result == true
   with_items:
     - "{{ base_repo_files.results }}"
