Fixes to support installation of older versions - updates as per review

diff --git a/roles/db-start/templates/start_all.sh.j2 b/roles/db-start/templates/start_all.sh.j2
--- a/roles/db-start/templates/start_all.sh.j2
+++ b/roles/db-start/templates/start_all.sh.j2
@@ -13,6 +13,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+rc=0
+
 while IFS=':' read -r ORACLE_SID ORACLE_HOME AUTOSTART_FLAG; do
     if [[ "$AUTOSTART_FLAG" =~ [Yy] ]]; then
         PATH_SAVE="$PATH"
@@ -24,7 +26,7 @@ while IFS=':' read -r ORACLE_SID ORACLE_HOME AUTOSTART_FLAG; do
             echo "Starting listener {{ listener_name }}"
             "$ORACLE_HOME"/bin/lsnrctl start {{ listener_name }}
         fi
-        if ! pgrep -f "ora_smon_$ORACLE_SID" ; then
+        if ! pgrep -f "[ora|db]_smon_$ORACLE_SID" ; then
             # startup is in separate sqlplus calls due to dbms_output not working correctly
             echo "Starting Oracle instance $ORACLE_SID"
             sqlplus -S / as sysdba <<EOF
@@ -35,6 +37,7 @@ EXIT;
 EOF
             if [ $? -ne 0 ]; then
                 echo "ERROR: Failed to mount $ORACLE_SID"
+                rc=1;
             else
                 IFS="," read -r db_role db_mode <<<"$(sqlplus -S / as sysdba <<EOF
 SET PAGES 0 FEED OFF VERIFY OFF HEADING OFF ECHO OFF COLSEP , TRIMSPOOL ON TAB OFF
@@ -53,6 +56,10 @@ SET PAGES 0 FEED OFF VERIFY OFF HEADING OFF ECHO OFF
 ALTER DATABASE OPEN;
 EXIT;
 EOF
+                        if [ $? -ne 0 ]; then
+                            echo "ERROR: Failed to open $ORACLE_SID"
+                            rc=2;
+                        fi
                     else
                         echo "Database is already open."
                     fi
@@ -62,13 +69,22 @@ EOF
 ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
 EXIT;
 EOF
+                    if [ $? -ne 0 ]; then
+                        echo "ERROR: Failed to start automatic MRP."
+                        rc=3;
+                    fi
                 else
                     echo "Unrecognized database role: $db_role. Database will remain in MOUNT mode."
+                    rc=4;
                 fi
             fi
+        else
+            echo "Oracle instance $ORACLE_SID is already running."
         fi
         PATH="$PATH_SAVE"
         LD_LIBRARY_PATH="$LD_LIBRARY_PATH_SAVE"
         export PATH LD_LIBRARY_PATH
     fi
 done < <(sed 's/#.*//; /^[[:space:]]*$/d' /etc/oratab)
+
+exit "$rc"
